### ISSUE TITLE
맨 위로 올라가는 버튼 구현

### ISSUE THREAD

**Issue by 2-hs2** [2-hs2/portfolio#16]
## Description
페이지 맨 위로 올라가는 버튼 구현하기
## Todo
- [x] 버튼 UI 생성
- [x] 버튼 기능 구현
- [x] 상세 페이지에 버튼 적용
## Etc
X

**Comment by 2-hs2** [comment]
[참고]
https://velog.io/@seoyul0203/REACT%ED%8E%98%EC%9D%B4%EC%A7%80-%EB%A7%A8%EC%9C%84%EB%A1%9C-%EC%9D%B4%EB%8F%99%ED%95%98%EB%8A%94-%EB%B2%84%ED%8A%BC-%EB%A7%8C%EB%93%A4%EA%B8%B0-scrollTo
