### ISSUE TITLE
시작 페이지 제작

### ISSUE THREAD

**Issue by 2-hs2** [2-hs2/portfolio#3]
## Description
포트폴리오의 첫 화면 제작
## Todo
- [x] 마우스 따라다니는 원형 요소 생성
- [x] 메인 제목 추가
- [x] 상세 내용 추가
- [x] 목차 페이지 이동 버튼 생성
- [x] 상세 내용 및 이동 버튼에 fadeIn, translateX 애니메이션 적용
## Etc
X
