### ISSUE TITLE
상세 페이지 틀 작업

### ISSUE THREAD

**Issue by 2-hs2** [2-hs2/portfolio#7]
## Description
상세 페이지에 공통으로 적용될 컴포넌트 개발
## Todo
- [x] 제목 및 인덱스 부분 생성
- [x] 작업 내용 소개 부분 생성
- [x] 링크 적용 부분 생성
## Etc
X
