### ISSUE TITLE
상세 페이지 내용 작성

### ISSUE THREAD

**Issue by 2-hs2** [2-hs2/portfolio#9]
## Description
상세 페이지에 세부 내용들을 적용한다.
## Todo
- [x] 앱 프로젝트 내용 적용
- [x] 파란학기 내용 적용
- [x] 미니 프로젝트 내용 적용
- [x] 디자인 내용 적용
## Etc
완성 후 배포 필요
